
export const LOGIN = 'LOGIN';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const LOGOUT = 'LOGOUT';
export const USER_PROFILE = 'USER_PROFILE'
export const ACTIVE_USER = 'ACTIVE_USER';
export const HOME_MOVIES_TOP = 'HOME_MOVIES_TOP'
export const TOP_PICK_MOVIES = 'TOP_PICK_MOVIES'
export const ALL_TOP_PICK_MOVIES = 'ALL_TOP_PICK_MOVIES'
export const FAN_FAVORITES_MOVIES = 'FAN_FAVORITES_MOVIES'
export const ALL_FAN_FAVORITES_MOVIES = 'ALL_FAN_FAVORITES_MOVIES'
export const RECENT_RELEASED_MOVIES = 'RECENT_RELEASED_MOVIES'
export const RECENT_UPCOMING_MOVIES = 'RECENT_UPCOMING_MOVIES'
export const PRIME_VIDEOS = 'PRIME_VIDEOS'
export const CELEBRITY_BIRTHDAY = 'CELEBRITY_BIRTHDAY'
export const MOVIE_DETAIL = 'MOVIE_DETAIL'
